param([int]$Port=9490)
$ErrorActionPreference='Stop';$edge='C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe';$profile=Join-Path $env:TEMP "curdun-p15-phase2-$Port";$proc=Start-Process $edge -ArgumentList @('--headless','--disable-gpu','--disable-extensions','--no-first-run','--remote-allow-origins=*',"--remote-debugging-port=$Port","--user-data-dir=$profile",'http://localhost:8000/app.html') -WindowStyle Hidden -PassThru;$ws=$null
try{$page=$null;for($i=0;$i-lt60-and!$page;$i++){Start-Sleep -Milliseconds 200;try{foreach($c in (Invoke-RestMethod "http://localhost:$Port/json/list")){if($c.type-eq'page'-and$c.url-like'http://localhost:8000/*'){$page=$c;break}}}catch{}};if(!$page){throw'No page'};$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$page.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null
$js=@'
(async()=>{const pause=ms=>new Promise(r=>setTimeout(r,ms));const wait=async(fn,l)=>{for(let i=0;i<150;i++){const v=fn();if(v)return v;await pause(100)}throw Error('Timeout '+l)};const fill=(e,v)=>{if(!e)throw Error('Missing input');e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))};const pin=async(id,digits)=>{await wait(()=>document.querySelector(`[data-login-id="${id}"]`),'staff '+id);document.querySelector(`[data-login-id="${id}"]`).click();await pause(180);for(const d of digits){[...document.querySelectorAll('[data-key]')].find(b=>b.dataset.key===d).click();await pause(130)}await wait(()=>S.posActiveUser?.id===id,'PIN '+id)};await wait(()=>typeof posPinLogin==='function','scripts');await posPinLogin('1234',3,1);S.view='pos';await posBootstrap();if(Number(S.posSession?.id)!==32)throw Error('Not session 32');const phaseStart=await posApiFetch('/pos/sessions/32/summary');if(Number(phaseStart.orders)!==7)throw Error('Phase 2 must start at seven orders');
// Visible lock, then Mohamed MINIMAL.
S.posView='backoffice';S.posBackofficeTab='dashboard';render();await pause(350);document.querySelector('#btn-topnav-user').click();await pause(180);document.querySelector('#btn-bo-lock').click();await wait(()=>!S.posActiveUser,'locked');const locked={session:Number(S.posSession.id),state:S.posSession.state,cashier:S.posActiveUser};await pin(4,'5678');if(Number(S.posSession.id)!==32)throw Error('Session changed on Mohamed PIN');
// Mohamed visible EVC sale: Sugar qty 1.
S.posView='session';S.posTab='checkout';S.posCart=[];posResetPaymentLines();render();await pause(350);const sugarBefore=POS_PRODUCTS.find(p=>p.id===3).stock;document.querySelector('[data-add-product="3"]').click();await wait(()=>S.posCart.length===1&&!S.posQuoteLoading,'Mohamed quote');const saleTotal=Number(S.posQuote.total);document.querySelector('[data-add-method="EVC Plus"]').click();await pause(300);fill(document.querySelector('.pos-pay-line-reference'),'P15-MOHAMED-EVC');await pause(300);document.querySelector('#btn-pos-charge').click();await wait(()=>S.posReceiptVisible,'Mohamed receipt');const mohamedReceipt=JSON.parse(JSON.stringify(S.posLastReceipt));await posBootstrap();const mohamedOrder=POS_TRANSACTIONS.find(t=>t.id===mohamedReceipt.id);S.posReceiptVisible=false;
// Lock back to Fartun.
S.posView='backoffice';S.posBackofficeTab='dashboard';render();await pause(300);document.querySelector('#btn-topnav-user').click();await pause(150);document.querySelector('#btn-bo-lock').click();await wait(()=>!S.posActiveUser,'second lock');await pin(3,'1234');if(Number(S.posSession.id)!==32)throw Error('Session changed on Fartun PIN');
// Partial refund order 220 / reference 000219, Sugar purchased qty 2, refund qty 1 Cash.
S.posView='backoffice';S.posBackofficeTab='orders';render();await pause(400);const refundLaunch=document.querySelector('[data-refund-txn="POS-20260822-01-000219"]');if(!refundLaunch)throw Error('Refund control missing');const refundStockBefore=POS_PRODUCTS.find(p=>p.id===3).stock;refundLaunch.click();await wait(()=>document.querySelector('.pos-refund-qty'),'refund modal');await pause(350);fill(document.querySelector('.pos-refund-qty'),'1');await pause(350);document.querySelector('.pos-refund-add-method[data-add-method="Cash"]').click();await pause(350);const refundAmount=Number(S.posRefundModal.payments[0].amount);document.querySelector('#btn-refund-submit').click();await wait(()=>S.posReceiptVisible&&S.posLastReceipt?.isRefund,'refund receipt');const refundReceipt=JSON.parse(JSON.stringify(S.posLastReceipt));await posBootstrap();S.posReceiptVisible=false;
// Visible Cash In and Cash Out.
const movement=async(button,amount,reason)=>{S.posView='backoffice';S.posBackofficeTab='sessions';render();await pause(350);document.querySelector(button).click();await wait(()=>document.querySelector('#rc-cash-amount'),'cash modal');await pause(300);fill(document.querySelector('#rc-cash-amount'),amount);fill(document.querySelector('#rc-cash-reason'),reason);await pause(250);document.querySelector('#rc-cash-submit').click();await wait(()=>!S.posRegisterModal,'cash saved');};await movement('#btn-cash-in',30,'Small bills / change');await movement('#btn-cash-out',20,'Supplies');
// Yusuf Customer Account settlement through real modal, Cash then EVC.
const settle=async(amount,method,reference='')=>{S.posView='backoffice';S.posBackofficeTab='customers';render();await pause(350);document.querySelector('[data-account-customer="3"]').click();await wait(()=>S.posCustomerAccount?.data&&!S.posCustomerAccount.loading,'Yusuf account');await pause(300);const before=Number(S.posCustomerAccount.data.customer.balance);document.querySelector('#btn-account-payment-open').click();await wait(()=>document.querySelector('#account-payment-amount'),'settlement form');await pause(300);fill(document.querySelector('#account-payment-amount'),amount);const select=document.querySelector('#account-payment-method');select.value=method;select.dispatchEvent(new Event('change',{bubbles:true}));await pause(350);if(reference)fill(document.querySelector('#account-payment-reference'),reference);document.querySelector('#btn-account-payment-submit').click();await wait(()=>S.posCustomerAccount?.data&&!S.posCustomerAccount.settleOpen&&!S.posCustomerAccount.submitting,'settled');const after=Number(S.posCustomerAccount.data.customer.balance);S.posCustomerAccount=null;return{method,amount,before,after}};const cashSettlement=await settle(10,'Cash');const digitalSettlement=await settle(5,'EVC Plus','P15-YUSUF-EVC');
const end=await posApiFetch('/pos/sessions/32/summary');return{locked,mohamed:{receipt:mohamedReceipt,order:mohamedOrder,stockBefore:sugarBefore,stockAfter:POS_PRODUCTS.find(p=>p.id===3).stock,total:saleTotal},refund:{original:220,receipt:refundReceipt,amount:refundAmount,stockBefore:refundStockBefore,stockAfter:POS_PRODUCTS.find(p=>p.id===3).stock},cashSettlement,digitalSettlement,phaseStart,end,session:Number(S.posSession.id),cashier:S.posActiveUser.name};})()
'@;$m=@{id=1;method='Runtime.evaluate';params=@{expression=$js;awaitPromise=$true;returnByValue=$true}}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($m);$ws.SendAsync([ArraySegment[byte]]::new($bytes),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;while(1){$buf=New-Object byte[] 1048576;$x=$ws.ReceiveAsync([ArraySegment[byte]]::new($buf),[Threading.CancellationToken]::None).GetAwaiter().GetResult();$r=([Text.Encoding]::UTF8.GetString($buf,0,$x.Count)|ConvertFrom-Json);if($r.id-eq1){if($r.result.exceptionDetails){throw($r.result.exceptionDetails|ConvertTo-Json -Depth 12)};$r.result.result.value|ConvertTo-Json -Depth 30;break}}}finally{if($ws){$ws.Dispose()};if($proc-and!$proc.HasExited){Stop-Process $proc.Id -Force}}
