param([int]$Port=9492)
$ErrorActionPreference='Stop';$edge='C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe';$profile=Join-Path $env:TEMP "curdun-p15-postclose-$Port";$proc=Start-Process $edge -ArgumentList @('--headless','--disable-gpu','--disable-extensions','--no-first-run','--remote-allow-origins=*',"--remote-debugging-port=$Port","--user-data-dir=$profile",'http://localhost:8000/app.html') -WindowStyle Hidden -PassThru;$ws=$null
try{$page=$null;for($i=0;$i-lt60-and!$page;$i++){Start-Sleep -Milliseconds 200;try{foreach($c in (Invoke-RestMethod "http://localhost:$Port/json/list")){if($c.type-eq'page'-and$c.url-like'http://localhost:8000/*'){$page=$c;break}}}catch{}};if(!$page){throw'No page'};$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$page.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null
$js=@'
(async()=>{
 const pause=ms=>new Promise(r=>setTimeout(r,ms));const wait=async(fn,l)=>{for(let i=0;i<180;i++){const v=fn();if(v)return v;await pause(100)}throw Error('Timeout '+l)};
 await wait(()=>typeof posBootstrap==='function','scripts');await posPinLogin('3456',6,1);await posBootstrap();
 if(S.posSession)throw Error('Register not closed after cold reload');if((S.posSessions||[]).some(s=>Number(s.id)===33))throw Error('Session 33 exists');
 const historical=await posApiFetch('/pos/sessions/32/summary');if(historical.session.state!=='CLOSED'||historical.session.closed_by_name!=='Khadija Abdi'||historical.session.closing_note!=='P15 full-day reconciliation')throw Error('Historical identity/note mismatch');
 S.view='pos';S.posView='backoffice';S.posBackofficeTab='dashboard';render();const menu=await wait(()=>document.querySelector('[data-nav-menu="reporting"]'),'reporting');await pause(300);menu.click();await pause(300);const item=await wait(()=>document.querySelector('[data-bo-tab="reports-session"]'),'session report');item.click();await pause(300);S.posSessions=(S.posSessions||[]).some(s=>Number(s.id)===32)?S.posSessions:[historical.session,...(S.posSessions||[])];S.posReportSelectedSessionId=32;S.posReportSelectedSummary=historical;const host=document.createElement('div');host.innerHTML=renderPOSReportSession();const visible=host.textContent.replace(/\s/g,'');
 for(const token of ['Session#32','CLOSED','NetSales$159.34','GrossSales$161.23','Refunds$1.89','ExpectedCash$258.93','CountedCash$258.93','Difference+0.00USD','P15full-dayreconciliation','FartunAli','MohamedFarah','Customer-accountcollections$15.00'])if(!visible.includes(token.replace(/\s/g,'')))throw Error('Historical report missing '+token);return{register:S.posSession,sessionCount33:(S.posSessions||[]).filter(s=>Number(s.id)===33).length,historical,visible:visible.slice(-5000)};
})()
'@;$m=@{id=1;method='Runtime.evaluate';params=@{expression=$js;awaitPromise=$true;returnByValue=$true}}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($m);$ws.SendAsync([ArraySegment[byte]]::new($bytes),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;while(1){$buf=New-Object byte[] 1048576;$x=$ws.ReceiveAsync([ArraySegment[byte]]::new($buf),[Threading.CancellationToken]::None).GetAwaiter().GetResult();$r=([Text.Encoding]::UTF8.GetString($buf,0,$x.Count)|ConvertFrom-Json);if($r.id-eq1){if($r.result.exceptionDetails){throw($r.result.exceptionDetails|ConvertTo-Json -Depth 12)};$r.result.result.value|ConvertTo-Json -Depth 40;break}}}finally{if($ws){$ws.Dispose()};if($proc-and!$proc.HasExited){Stop-Process $proc.Id -Force}}
