param([int]$Port=9480)
$ErrorActionPreference='Stop';$edge='C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe';$profile=Join-Path $env:TEMP "curdun-p15-sales-$Port";$proc=Start-Process $edge -ArgumentList @('--headless','--disable-gpu','--disable-extensions','--no-first-run','--remote-allow-origins=*',"--remote-debugging-port=$Port","--user-data-dir=$profile",'http://localhost:8000/app.html') -WindowStyle Hidden -PassThru;$ws=$null
try{$page=$null;for($i=0;$i-lt60-and!$page;$i++){Start-Sleep -Milliseconds 200;try{foreach($c in (Invoke-RestMethod "http://localhost:$Port/json/list")){if($c.type-eq'page'-and$c.url-like'http://localhost:8000/*'){$page=$c;break}}}catch{}};if(!$page){throw'No page'};$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$page.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null
$js=@'
(async()=>{const pause=ms=>new Promise(r=>setTimeout(r,ms));const wait=async(fn,l)=>{for(let i=0;i<150;i++){const v=fn();if(v)return v;await pause(100)}throw Error('Timeout '+l)};const change=(e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))};await wait(()=>typeof posPinLogin==='function','scripts');await posPinLogin('1234',3,1);S.view='pos';await posBootstrap();if(Number(S.posSession?.id)!==32||S.posSession.state!=='OPENED')throw Error('P15 session #32 is not the only current session');if(S.posActiveUser?.id!==3)throw Error('Fartun not active');const startSummary=await posApiFetch('/pos/sessions/32/summary');const startOrders=Number(startSummary.orders||0);const results=[];
const start=async(productId,qty=1)=>{S.posView='session';S.posTab='checkout';S.posReceiptVisible=false;S.posCart=[];S.posDebtCustomerId=null;S.posSelectedPricelistId=null;S.posPricelistManual=false;S.posSelectedRewardId=null;S.posRewardsOpen=false;posResetPaymentLines();render();await pause(350);const p=POS_PRODUCTS.find(x=>x.id===productId),stock=p.stock;document.querySelector(`[data-add-product="${productId}"]`).click();await wait(()=>S.posCart.length===1&&!S.posQuoteLoading,'initial quote');while(S.posCart[0].qty<qty){document.querySelector('[data-qty-plus="0"]').click();await wait(()=>!S.posQuoteLoading&&Number(S.posQuote.lines[0].qty)===S.posCart[0].qty,'qty quote')}return{p,stock};};
const customer=async id=>{const e=document.querySelector('#pos-deyn-customer');e.value=String(id);e.dispatchEvent(new Event('change',{bubbles:true}));await wait(()=>Number(S.posDebtCustomerId)===id&&!S.posQuoteLoading&&S.posCustomerLoyalty?.customer,'customer quote');await pause(350)};
const addPay=async(name,amount,reference=null,tendered=null)=>{const b=[...document.querySelectorAll('[data-add-method]')].find(x=>x.dataset.addMethod===name);if(!b)throw Error('Missing method '+name);b.click();await pause(180);const i=S.posPaymentLines.length-1;let row=document.querySelector(`.pos-pay-line[data-line-idx="${i}"]`);change(row.querySelector('.pos-pay-line-amount'),amount);await pause(100);row=document.querySelector(`.pos-pay-line[data-line-idx="${i}"]`);if(reference!==null)change(row.querySelector('.pos-pay-line-reference'),reference);if(tendered!==null){await pause(100);row=document.querySelector(`.pos-pay-line[data-line-idx="${i}"]`);change(row.querySelector('.pos-pay-line-tendered'),tendered)}await pause(180)};
const finish=async(label,before,extra={})=>{await wait(()=>!document.querySelector('#btn-pos-charge').disabled,label+' validate');document.querySelector('#btn-pos-charge').click();await wait(()=>S.posReceiptVisible&&S.posLastReceipt,label+' receipt');const receipt=JSON.parse(JSON.stringify(S.posLastReceipt));await posBootstrap();const order=POS_TRANSACTIONS.find(t=>t.id===receipt.id);results.push({label,receipt,order,stock:{product_id:before.p.id,before:before.stock,after:POS_PRODUCTS.find(p=>p.id===before.p.id).stock},...extra});S.posReceiptVisible=false;return receipt};
// S1 cash, tender greater than amount.
let b,total;if(startOrders<1){b=await start(2,1);total=Number(S.posQuote.total);await addPay('Cash',total,null,total+10);await finish('S1_CASH',b,{quoted_total:total,tendered:total+10});}
// S2 EVC Plus.
if(startOrders<2){b=await start(3,2);total=Number(S.posQuote.total);await addPay('EVC Plus',total,'P15-EVC-S2');await finish('S2_EVC',b,{quoted_total:total});}
// S3 Cash + EVC + ZAAD.
if(startOrders<3){b=await start(2,2);total=Number(S.posQuote.total);const a=Number((total/3).toFixed(2)),c=Number((total-a-a).toFixed(2));await addPay('Cash',a,null,a);await addPay('EVC Plus',a,'P15-EVC-S3');await addPay('ZAAD',c,'P15-ZAAD-S3');await finish('S3_SPLIT',b,{quoted_total:total,allocation:{cash:a,evc:a,zaad:c}});}
// S4 canonical Promotion threshold.
if(startOrders<4){b=await start(1,10);const pl=S.posPricelists.find(x=>x.name==='Promotion');if(!pl)throw Error('Promotion missing');const pe=document.querySelector('#pos-pricelist-select');pe.value=String(pl.id);pe.dispatchEvent(new Event('change',{bubbles:true}));await wait(()=>Number(S.posSelectedPricelistId)===Number(pl.id)&&!S.posQuoteLoading,'Promotion quote');const q4=JSON.parse(JSON.stringify(S.posQuote)),line4=q4.lines[0];if(Number(line4.final_unit_price)!==10.5)throw Error('Promotion unit is not 10.50');total=Number(q4.total);await addPay('Cash',total,null,total);await finish('S4_PROMOTION',b,{quote:{pricelist:q4.pricelist,line:line4,total}});}
// S5 Abdi reward, cash only.
if(startOrders<5){b=await start(2,1);await customer(1);const abdiBefore=POS_CUSTOMERS.find(c=>c.id===1),loyaltyBefore=Number(abdiBefore.points),debtBefore=Number(abdiBefore.debtBalance);const rewards=await wait(()=>document.querySelector('#btn-pos-rewards'),'Rewards control');rewards.click();await wait(()=>document.querySelector('[data-loyalty-reward]'),'eligible reward');await pause(350);const rb=document.querySelector('[data-loyalty-reward]'),rewardId=Number(rb.dataset.loyaltyReward);rb.click();await wait(()=>Number(S.posSelectedRewardId)===rewardId&&!S.posQuoteLoading,'reward quote');const q5=JSON.parse(JSON.stringify(S.posQuote));total=Number(q5.total);await addPay('Cash',total,null,total);await finish('S5_LOYALTY',b,{customer_id:1,before:{points:loyaltyBefore,debt:debtBefore},reward:{id:rewardId,quote:q5.loyalty,discount:q5.discounts.loyalty},after:{points:Number(POS_CUSTOMERS.find(c=>c.id===1).points),debt:Number(POS_CUSTOMERS.find(c=>c.id===1).debtBalance)}});}
// S6 Yusuf Cash + Deyn.
if(startOrders<6){b=await start(3,3);await customer(3);const yBefore=Number(POS_CUSTOMERS.find(c=>c.id===3).debtBalance);total=Number(S.posQuote.total);const cash=Number((total/2).toFixed(2)),deyn=Number((total-cash).toFixed(2));await addPay('Cash',cash,null,cash);await addPay('Deyn',deyn);await finish('S6_DEYN',b,{customer_id:3,allocation:{cash,deyn},debt:{before:yBefore,after:Number(POS_CUSTOMERS.find(c=>c.id===3).debtBalance)}});}
if(startOrders===6){b=await start(2,1);total=Number(S.posQuote.total);await addPay('Cash',total);await pause(400);change(document.querySelector('.pos-pay-line-tendered'),total+10);await pause(400);await finish('S1B_OVERTENDER',b,{quoted_total:total,tendered:total+10});}
const endSummary=await posApiFetch('/pos/sessions/32/summary');return{session_id:32,cashier:S.posActiveUser.name,startOrders,endOrders:Number(endSummary.orders||0),ordersAdded:Number(endSummary.orders||0)-startOrders,startSummary,endSummary,results};})()
'@;$m=@{id=1;method='Runtime.evaluate';params=@{expression=$js;awaitPromise=$true;returnByValue=$true}}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($m);$ws.SendAsync([ArraySegment[byte]]::new($bytes),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;while(1){$buf=New-Object byte[] 1048576;$x=$ws.ReceiveAsync([ArraySegment[byte]]::new($buf),[Threading.CancellationToken]::None).GetAwaiter().GetResult();$r=([Text.Encoding]::UTF8.GetString($buf,0,$x.Count)|ConvertFrom-Json);if($r.id-eq1){if($r.result.exceptionDetails){throw($r.result.exceptionDetails|ConvertTo-Json -Depth 10)};$r.result.result.value|ConvertTo-Json -Depth 30;break}}}finally{if($ws){$ws.Dispose()};if($proc-and!$proc.HasExited){Stop-Process $proc.Id -Force}}
